name: mass_manager
description: A meal and expense management app for shared households or dormitories.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sqflite: ^2.4.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  fl_chart: ^0.70.2
  pdf: ^3.10.4
  cached_network_image: ^3.2.3
  flutter_local_notifications: ^19.1.0
  uuid: ^4.5.1
  connectivity_plus: ^4.0.1
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  lottie: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
#        - asset: assets/fonts/Poppins-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Poppins-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/Poppins-Bold.ttf
#          weight: 700